name: Release Asset

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build YouTrack App
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm run build

      - name: Pack YouTrack App
        run: npm run pack

      - name: Upload asset to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${{ github.event.release.tag_name }}" youtrack-real-quick-notes-app.zip --clobber
